title: Summenzeichen auflösen
question: |
  Berechnen Sie die folgenden Summen
  
  a) $\sum_{i=1}^{5}3i$
  
  b) $\sum_{j=3}^{9}(2j-1)$
  
  c) $\sum_{k=1}^{1}k$
  
  d) $\sum_{i=0}^{9}3$
  
  e) $\sum_{i=2}^{4}(k\cdot 2) + \sum_{i=0}^{4} (\frac{1}{2}j)$
  
  f) $\sum_{i=-5}^{5}k$
  
  g) $\sum_{i=-5}^{-3}k$
  
  h) $\sum_{i=2}^{1}k$

solution: |
  a) $\sum_{i=1}^{5}3i = 3\cdot 1 + 3\cdot 2 + 3\cdot 3 + 3\cdot 4 + 3\cdot 5 = 3+6+9+12+15 = 45$
  
  b) $\sum_{j=3}^{9}(2j-1) = 5 + 7 + 9 + 11 + 13 + 15+ 17 = 77$
  
  c) $\sum_{k=1}^{1}k = 1$
  
  d) $\sum_{i=0}^{9}3 = 3 + 3 + 3 + 3 + 3 + 3 + 3 + 3 + 3 + 3 = 10 \cdot 3 = 30$
  
  e) $\sum_{i=2}^{4}(k\cdot 2) + \sum_{i=0}^{4} (\frac{1}{2}j) = (2\cdot 2 + 3\cdot 2 + 4\cdot 2 )+  (\frac{1}{2}\cdot 0)+(\frac{1}{2}\cdot 1)+(\frac{1}{2}\cdot 2)+(\frac{1}{2}\cdot 3)+(\frac{1}{2}\cdot 4)$
  
  f) $\sum_{i=-5}^{5}k = (-5)+(-4)+(-3)+(-2)+(-1) + 0 + 1 + 2 + 3 + 4 + 5 = 0$
  
  g) $\sum_{i=-5}^{-3}k = (-5)+(-4)+(-3) = -12$
  
  h) $\sum_{i=2}^{1}k = 0$, da der obere Index kleiner ist als der untere (leere Summe).
